version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports: 
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./app/:/var/www/html
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      - internal
    environment:
      XDEBUG_MODE: debug
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./app/:/var/www/html
networks:
  internal:
    driver: bridge